project:
  type: website
  output-dir: ../_site

website:
  title: "Modelo de Lluvia Chile 2026"
  navbar:
    left:
      - text: "Resumen Ejecutivo"
        href: index.qmd
      - text: "Análisis Exploratorio (AED)"
        href: aed.qmd
      - text: "Modelo & EVT"
        href: modelo.qmd
    right:
      - icon: github
        href: https://github.com/pablozunigac/lluvias-chile-2026
      - icon: globe
        href: https://pablozunigac.github.io

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    smooth-scroll: true